apiVersion: v1
kind: Service
metadata:
  name: devops-service
spec:
  selector:
    app: devops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
  serviceAccountName: default
